sudo: false
language: node_js
node_js:
  - '3'
  - '2'
  - '1'
  - '0.12'
script:
  - 'npm run test-travis'
after_script:
  - 'npm i codecov.io && cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js'
